name: Build
on: [ workflow_dispatch ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.19.2, 1.20.1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@main
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup Fabric files
        run: ./gradlew fabric:setupFiles -PminecraftVersion="${{ matrix.minecraft }}" -PpatreonApiKey="${{ secrets.PATREON_API_KEY }}"
      - name: Setup Forge files
        run: ./gradlew forge:setupFiles -PminecraftVersion="${{ matrix.minecraft }}" -PpatreonApiKey="${{ secrets.PATREON_API_KEY }}"
      - name: Build ${{ matrix.minecraft }} (server)
        run: ./gradlew build -PminecraftVersion="${{ matrix.minecraft }}" -PexcludeAssets=true
      - name: Capture release artifacts
        uses: actions/upload-artifact@main
        with:
          name: Fabric and Forge ${{ matrix.minecraft }}
          path: build/release/
